from .base import TrainerConsoleFrontend
from .sentence_translation import SentenceTranslationTrainerConsoleFrontend
from .vocable_trainer import VocableTrainerConsoleFrontend
from .vocable_adder import VocableAdderFrontend
